/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'excited' : IDL.Null,
  'neutral' : IDL.Null,
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mood' : Mood,
  'timestamp' : Time,
});
export const Note = IDL.Record({ 'text' : IDL.Text, 'completed' : IDL.Bool });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyMood = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'avatarOutfitColor' : IDL.Text,
  'name' : IDL.Text,
  'themePreference' : IDL.Text,
  'avatarSkinTone' : IDL.Text,
  'avatarHairStyle' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});
export const AllUserData = IDL.Record({
  'tasks' : IDL.Vec(Note),
  'moodLog' : IDL.Vec(DailyMood),
  'journal' : IDL.Vec(JournalEntry),
  'profile' : UserProfile,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([JournalEntry], [], []),
  'addNote' : IDL.Func([Note], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserData' : IDL.Func([], [IDL.Opt(AllUserData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMoodLogByDay' : IDL.Func([Time], [IDL.Vec(DailyMood)], ['query']),
  'getSortedJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getTaskList' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDailyMood' : IDL.Func([DailyMood], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'excited' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mood' : Mood,
    'timestamp' : Time,
  });
  const Note = IDL.Record({ 'text' : IDL.Text, 'completed' : IDL.Bool });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyMood = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'avatarOutfitColor' : IDL.Text,
    'name' : IDL.Text,
    'themePreference' : IDL.Text,
    'avatarSkinTone' : IDL.Text,
    'avatarHairStyle' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  const AllUserData = IDL.Record({
    'tasks' : IDL.Vec(Note),
    'moodLog' : IDL.Vec(DailyMood),
    'journal' : IDL.Vec(JournalEntry),
    'profile' : UserProfile,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([JournalEntry], [], []),
    'addNote' : IDL.Func([Note], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserData' : IDL.Func([], [IDL.Opt(AllUserData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMoodLogByDay' : IDL.Func([Time], [IDL.Vec(DailyMood)], ['query']),
    'getSortedJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getTaskList' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDailyMood' : IDL.Func([DailyMood], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };