/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllUserData {
  'tasks' : Array<Note>,
  'moodLog' : Array<DailyMood>,
  'journal' : Array<JournalEntry>,
  'profile' : UserProfile,
}
export interface DailyMood { 'mood' : Mood, 'timestamp' : Time }
export interface JournalEntry {
  'title' : string,
  'body' : string,
  'mood' : Mood,
  'timestamp' : Time,
}
export type Mood = { 'sad' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'excited' : null } |
  { 'neutral' : null };
export interface Note { 'text' : string, 'completed' : boolean }
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'avatarOutfitColor' : string,
  'name' : string,
  'themePreference' : string,
  'avatarSkinTone' : string,
  'avatarHairStyle' : string,
  'profilePhotoUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[JournalEntry], undefined>,
  'addNote' : ActorMethod<[Note], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserData' : ActorMethod<[], [] | [AllUserData]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMoodLogByDay' : ActorMethod<[Time], Array<DailyMood>>,
  'getSortedJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getTaskList' : ActorMethod<[], Array<Note>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDailyMood' : ActorMethod<[DailyMood], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];